name: RS app deployment 

on: 
   workflow_run:
    workflows: ["CI Workflow"]  # Must match `name:` in ci.yml
    types:
      - completed
   workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: read 
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy ride sharing app to gh pages
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps: 
      # Checkout the gh-pages branch
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          persist-credentials: true      

      # Setup Git credentials
      - name: Setup Git credentials with PAT
        run: |
          git config --global user.email "adharjain@gmail.com"
          git config --global user.name "adhar-jain"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}

      # Clean the gh-pages branch
      - name: Clean gh-pages branch
        run: |
          git rm -rf . || true
          git clean -fdx

      # Download the artifact uploaded during the CI workflow
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      # Debug dist directory
      - name: Debug dist directory
        run: ls -R dist

      # Copy all files from dist to the root of the repository
      - name: Copy files from dist to root
        run: cp -r dist/browser/. .

      # Append a timestamp to index.html to force a change
      - name: Append timestamp to index.html
        run: echo "<!-- Deployed at $(date) -->" >> ./index.html

      # Commit and push changes to the gh-pages branch
      - name: Commit and push to gh-pages branch
        run: |
          git add -A
          git commit -m "Deploy to GitHub Pages - $(date)" || echo "No changes to commit"
          git push origin gh-pages --force