name: build-test-deploy

on: 
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v2
        with:
            persist-credentials: false
      - name: Debug branch state
        run: git log -1
      - name: use node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build -- --output-path=dist --base-href=/ride-sharing-app/
      - name: Add .nojekyll
        run: echo > .nojekyll
      - name: Debug dist directory
        run: ls -R dist
      - name: Setup Git credentials
        run: |
          git config --global user.email "adharjain@gmail.com"
          git config --global user.name "adhar-jain"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard
      
      - name: Copy index.html to index.html
        run: |
          cp dist/browser/test/index.html dist/index.html
      
      - name: Commit and push to gh-pages branch
        run: |
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force
        
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download dist artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    - name: Debug working directory
      run: pwd
    - name: List dist directory after download
      run: ls -R dist
    - name: Copy files from dist to root
      run: cp -r dist/. .
    - name: List working directory for debug
      run: ls -R .
