name: build-test-deploy

on: 
  push:
    branches:
      - main
  workflow_dispatch:  

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build -- --output-path=dist --base-href=/ride-sharing-app/
      - name: verify index.html
        run: if [ ! -f dist/browser/index.html ]; then echo "index.html not found in browser directory!"; exit 1; fi
      - name: copy index.html to dist root
        run: cp dist/browser/index.html dist/index.html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: production
    steps:
      - name: checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: copy built files to gh-pages branch
        run: |
          git rm -rf .
          cp -r ../dist/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
      - name: push to gh-pages branch
        run: git push origin gh-pages
      - name: configure github pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: none
      - name: echo deployment URL
        run: echo "Deployed to ${{ steps.deployment.outputs.page_url }}"
