name: build-test-deploy

on: 
  push:
  workflow_dispatch:  

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build -- --output-path=dist --base-href=/ride-sharing-app/

  deploy:
    needs: build
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: use node.js        
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: configure github pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      - run: npm install
      - run: npm run build -- --output-path=dist --base-href=/ride-sharing-app/
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with: 
          path: './dist'
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
      - name: echo deployment URL
        run: echo "Deployed to ${{ steps.deployment.outputs.page_url }}"
