name: build-test-deploy

on: 
  push:
    branches:
      - main
      - gh-pages
  workflow_dispatch:  

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build -- --output-path=dist --base-href=/ride-sharing-app/
      - name: list dist directory for debug
        run: ls -R dist
      - name: copy index.html to dist root
        run: cp dist/browser/test/index.html dist/index.html
      - name: verify index.html
        run: if [ ! -f dist/index.html ]; then echo "index.html not found in dist directory!"; exit 1; fi
      - name: upload dist artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          persist-credentials: false
      - name: clean gh-pages branch
        run: |
          git rm -rf .
          git clean -fdx
      - name: copy built files to gh-pages branch
        run: cp -r dist/* .
      - name: list working directory for debug
        run: ls -R .
      - name: commit and push to gh-pages branch
        run: |
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
      - name: echo deployment URL
        run: echo "Deployed to https://adhar-jain.github.io/ride-sharing-app/"
