name: build-test-deploy

on: 
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v2
      - name: use node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build -- --base-href=/ride-sharing-app/
      - name: Add .nojekyll
        run: echo > .nojekyll
      - name: list dist directory for debug
        run: ls -R dist
      - name: copy index.html to dist root
        run: cp dist/browser/index.html dist/index.html
      - name: verify index.html
        run: if [ ! -f dist/index.html ]; then echo "index.html not found in dist directory!"; exit 1; fi
      - name: list dist directory after index.html copy for debug
        run: ls -R dist
      - name: upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
      - name: Debug workspace
        run: ls -R /home/runner/work/ride-sharing-app/ride-sharing-app  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download dist artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    - name: Debug working directory
      run: pwd
    - name: List dist directory after download
      run: ls -R dist
    - name: Copy files from dist to root
      run: cp -r dist/. .
    - name: List working directory for debug
      run: ls -R .
