name: RS app deployment 

on: 
   workflow_run:
    workflows: ["CI Workflow"]  # Must match `name:` in ci.yml
    types:
      - completed
   workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write 
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy ride sharing app to gh pages
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps: 
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          npm install
          ng build --configuration production --base-href /ride-sharing-app/

      # Deploy to gh-pages branch
      - name: Deploy to gh-pages
        run: |
          git config --global user.email "adharjain@gmail.com"
          git config --global user.name "adhar-jain"
          # Ensure the gh-pages branch exists
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
          fi
          # Clean the gh-pages branch
          git rm -rf .
          # Copy only the built files to the root of the gh-pages branch
          cp -r dist/ride-sharing-app/* .
          # Add and commit changes
          git add -A
          git commit -m "Deploy to GitHub Pages - $(date)"
          # Force push to gh-pages branch
          git push -f origin gh-pages