name: RS app deployment 

on: 
   workflow_run:
    workflows: ["CI Workflow"]  # Must match `name:` in ci.yml
    types:
      - completed
   workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: read 
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy ride sharing app to gh pages
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps: 
      # Check and create gh-pages branch
      - name: Check and create gh-pages branch
        run: |
          if ! git show-ref --quiet refs/heads/gh-pages; then
            git branch gh-pages
          fi

       # Checkout the gh-pages branch
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
         ref: gh-pages
         persist-credentials: true          

      # Setup Git credentials
      - name: Setup Git credentials with PAT
        run: |
          git config --global user.email "adharjain@gmail.com"
          git config --global user.name "adhar-jain"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}

      # # Clean the gh-pages branch
      # - name: Clean the gh-pages branch
      #   run: |
      #     git rm -rf . || true
      #     git clean -fdx

        # Debug gh-pages branch - After copying files
      - name: Debug gh-pages branch - Before
        run: |
          ls -la  
          echo '--------'
          ls -R

      # Download the artifact uploaded during the build job
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/ride-sharing-app

      - name: Debug gh-pages branch - Middle
        run: |
          ls -la  
          echo '--------'
          ls -R
      
      - name: Copy files from dist to root
        run: cp -r dist/browser/* .

      # Copy all files from dist to the root of the repository
      #- name: Copy files from dist to root
      #  run:  | 
      #        cp dist/ride-sharing-app/browser/index.html ./index.html

      - name: Debug gh-pages branch - After
        run: ls -R

      # Append a timestamp to index.html to force a change
      - name: Append timestamp to index.html
        run: echo "<!-- Deployed at $(date) -->" >> ./index.html

      # # Debug gh-pages branch - After copying files
      # - name: Debug gh-pages branch
      #   run: ls -R

      # Commit and push changes to the gh-pages branch
      - name: Commit and push to gh-pages branch
        run: |
          git add -A
          git commit -m "Deploy to GitHub Pages - $(date)" || echo "No changes to commit"
          git push origin gh-pages --force