name: build-test-deploy

on: 
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v2
      - name: use node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build -- --output-path=dist --base-href=/ride-sharing-app/
      - name: Add .nojekyll
        run: echo > .nojekyll
      - name: Debug dist directory
        run: ls -R dist
      - name: Copy index.html to index.html
        run: |
          cp dist/ride-sharing-app/browser/test/index.html dist/index.html
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download dist artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    - name: Debug working directory
      run: pwd
    - name: List dist directory after download
      run: ls -R dist
    - name: Copy files from dist to root
      run: cp -r dist/. .
    - name: List working directory for debug
      run: ls -R .
