name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --output-path=dist --base-href=/ride-sharing-app/

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish-dir: ./dist
          publish-branch: gh-pages
          publish-repo: ${{ github.repository }}
          publish-path: /
          commit-message: "Deploy to GitHub Pages"
          force: true
          branch: gh-pages