name: Continous Integration for ride sharing app

on: 
    push:
        branches: [main]
    pull_request:

jobs:
    angular-app:
        name: Build & Test Angular App
        runs-on: ubuntu-latest

        steps:
            #Checkout code
            - name: check out code
              uses: actions/checkout@v4
              
            #setup node.js
            - name: setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 18

            #Install dependencies
            - name: Install Dependencies
              run: mkdir ui
            - run: npm ci
              working-directory: ./ui

            #Run unit tests
            - name: Lint and Test
              run: |
                npm install --save-dev karma-chrome-launcher
                npm run lint -- --force --max-warnings=0
                npm run test -- --watch=false --browsers=ChromeHeadless
              working-directory: ./ui

            #Build artifact
            - name: Build artifacts
              run: npm run build
              working-directory: ./ui

            #Security scans (Veracode, Black Duck)
            

            #Upload artifacts (optional, for later CD step)
            # Upload the dist directory as an artifact
            - name: Upload dist artifact
              uses: actions/upload-artifact@v4
              with:
                name: dist
                path: dist/ride-sharing-app